# Generated by Django 2.1 on 2018-09-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Benutzername', models.CharField(max_length=8)),
                ('Passwort', models.CharField(max_length=32)),
            ],
        ),
    ]
